apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-limiter-service
  template:
    metadata:
      labels:
        app: rate-limiter-service
    spec:
      containers:
        - name: rate-limiter
          image: rate-limiter:latest
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOST
              value: "redis:6379"
            - name: CASSANDRA_HOST
              value: "cassandra:9042"
---
apiVersion: v1
kind: Service
metadata:
  name: rate-limiter-service
spec:
  ports:
    - port: 8081
  selector:
    app: rate-limiter-service